name: flutter_diacare
description: A doctor prescription app with advanced features.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Firebase for authentication, chat, and storage
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  # Video call (Agora)
  agora_rtc_engine: ^6.5.3

  # Chat UI
  flutter_chat_ui: ^1.6.10

  # HTTP requests (for AI/REST APIs)
  http: ^1.2.1

  # UI and utilities
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.4

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
